use chrono::{DateTime, Local};
use std::fmt;

/// Severity levels for alerts - drives color coding and sort priority.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
    Danger,
}

impl fmt::Display for AlertSeverity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AlertSeverity::Info => write!(f, "INFO"),
            AlertSeverity::Warning => write!(f, "WARN"),
            AlertSeverity::Critical => write!(f, "CRIT"),
            AlertSeverity::Danger => write!(f, "DANGER"),
        }
    }
}

/// Category of the alert for filtering and grouping.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlertCategory {
    HighCpu,
    HighMemory,
    HighDiskIo,
    Zombie,
    Suspicious,
    SystemOverload,
    MemoryLeak,
    SecurityThreat,
}

impl fmt::Display for AlertCategory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AlertCategory::HighCpu => write!(f, "CPU"),
            AlertCategory::HighMemory => write!(f, "MEM"),
            AlertCategory::HighDiskIo => write!(f, "DISK"),
            AlertCategory::Zombie => write!(f, "ZOMBIE"),
            AlertCategory::Suspicious => write!(f, "SUSPECT"),
            AlertCategory::SystemOverload => write!(f, "OVERLOAD"),
            AlertCategory::MemoryLeak => write!(f, "LEAK"),
            AlertCategory::SecurityThreat => write!(f, "SECURITY"),
        }
    }
}

/// A single alert event generated by the detection engine.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct Alert {
    pub severity: AlertSeverity,
    pub category: AlertCategory,
    pub process_name: String,
    pub pid: u32,
    pub message: String,
    pub timestamp: DateTime<Local>,
    pub value: f64,
    pub threshold: f64,
}

impl Alert {
    pub fn new(
        severity: AlertSeverity,
        category: AlertCategory,
        process_name: &str,
        pid: u32,
        message: String,
        value: f64,
        threshold: f64,
    ) -> Self {
        Self {
            severity,
            category,
            process_name: process_name.to_string(),
            pid,
            message,
            timestamp: Local::now(),
            value,
            threshold,
        }
    }

    pub fn age_display(&self) -> String {
        let elapsed = Local::now()
            .signed_duration_since(self.timestamp)
            .num_seconds();
        if elapsed < 60 {
            format!("{}s ago", elapsed)
        } else if elapsed < 3600 {
            format!("{}m ago", elapsed / 60)
        } else {
            format!("{}h ago", elapsed / 3600)
        }
    }
}
